let sanonnat = ['"Taiteilijat ovat tavattoman herkkiä. — Nipsu, Tove Jansson"', 
                '"Senkin röyhkimys! Minä olen täyteläinen! — Niiskuneiti, Tove Jansson"', 
                '"Takaisin luontoon. Elämme vain kerran. Hiiteen velvollisuudet. — Muumipappa, Tove Jansson"', 
                '"Tuollainen sinäkin olit tuhat vuotta sitten. — Tove Jansson, Tuu-tikki"', 
                '"Mörkö, olisimme iloisia jos menisit kotiin. — Muumimamma, Tove Jansson"', 
                '"Vahinko etteivät äidit saa lähteä milloin heitä huvittaa ja ruveta nukkumaan ulkosalla. Varsinkin äidit sitä toisinaan tarvitsisivat. — Muumimamma, Tove Jansson"', 
                '"Minä en jätä huomiseen mitään, minkä voin tehdä tänään. — Pikku Myy, Tove Jansson"', 
                '"Kyllä on jännittävää elää, ajatteli Muumipeikko. Kaikki voi hetkessä kääntyä ihan ylösalaisin – ilman mitään syytä. — Muumipeikko, Tove Jansson"', 
                '"Se on kyllä hyvin pieni eläin. Odotahan, niin valaisen sitä. Kaikki näyttää vaarallisemmalta pimeässä, käsitäthän. — Muumipappa, Tove Jansson"', 
                '"Ikinä ei tule aivan vapaaksi, jos ihailee toista liikaa, sen minä tiedän. — Nuuskamuikkunen, Tove Jansson"', 
                '"Ajattelen sitä aamulla, se ei mahdu juuri nyt päähäni. — Muumipeikko, Tove Jansson"', 
                '"Minä en siedä lääppimistä, minä tahdon paljon lahjoja!  — Pikku Myy, Tove Jansson"', 
                '"Saattaa olla, että kupillinen teetä viinimarjamehun kera voisi pelastaa minut, mutta eihän sitä koskaan tiedä. — Niiskuneiti, Tove Jansson"', 
                '"Älä ajattele ikäviä asioita, se on minun mottoni! — Niiskuneiti, Tove Jansson"', 
                '"Maailma on täynnä suuria ihmeitä sille, joka on valmis ottamaan niitä vastaan. — Muumipappa, Tove Jansson"', 
                '"Eihän sitä aina voi olla ystävällinen ja seurallinen. Ei yksinkertaisesti ehdi. — Nuuskamuikkunen, Tove Jansson"', 
                '"Sellainen henkilö, joka syö pannukakkua ja hilloa, ei voi olla kauhean vaarallinen. — Pikku Myy, Tove Jansson"', 
                '"Minä en poimi kukkasia enkä lahjoita kenellekään suklaarasioita. Minä popsin suklaat itse! — Nipsu, Tove Jansson"', 
                '"Kun minä jotakin jysäytän, niin se ei totisesti ole mikään kamelin pieru! — Noita, Tove Jansson"', 
                '"Ironisia henkilöitä ei kannata piestä. — Tove Jansson, Tuu-tikki"', 
                '"Pienuuttani minä kompensoin ilkeydellä. — Pikku Myy, Tove Jansson"', 
                '"Yksi asia sinussa on mainio, Hemuli sanoi luottamuksellisesti. Sinä puhut niin vähän. Sinä vaikutat kamalan viisaalta sen takia ettet koskaan sano mitään. — Hemuli, Tove Jansson"', 
                '"Ellei joku satu tietämään mitä eläkkeelle pääseminen merkitsee, niin kerrotaan asia: kun tulee tarpeeksi vanhaksi, saa kaikessa rauhassa tehdä juuri mitä haluaa. — Hemuli, Tove Jansson"', 
                '"Kuinka minä voin elää ellen saa siivota enkä laittaa ruokaa? Eihän maailmassa ole mitään muuta mikä maksaa vaivan. — Tove Jansson, Viljonkka"', 
                '"Seuraavana keväänä minun on herättävä ennen muita. Silloin saa olla hetken rauhassa ja tehdä mitä haluaa. — Muumimamma, Tove Jansson"', 
                '"Pienikin olento voi olla hyvin rohkea. — Muumipappa, Tove Jansson"', 
                '"Kummallista miten hyvin välistä ymmärtää toisiaan puhumatta. — Muumipappa, Tove Jansson"', 
                '"Pidä varasi ettet päästä asioita kasvamaan liian suuriksi. — Nuuskamuikkunen, Tove Jansson"', 
                '"Jos kaksi höperöä asuu samassa saaressa, niin he joko tietävät toisistaan kaiken tai eivät halua tietää toisistaan mitään. — Pikku Myy, Tove Jansson"']


module.exports = {sanonnat};